%%{init: {"theme":"base","themeCSS": "#Argument rect{stroke:transparent; fill:#e5e5e5} #Argument span {color:transparent} .edgeLabel{color:#888; font-size:0.9em; margin-right:3px} .edgeLabel i{color:crimson} .edge-pattern-dotted{stroke:crimson} .edge-pattern-solid{stroke:green} #flowchart-pointEnd{fill:green} g[id*=\"O\"] *{stroke:crimson!important; font-size:1em} circle+g span{color:white; } circle{fill:green!important} g[id*=\"C\"] * {fill:black;color:white;font-weight:bold} g[id*=\"V\"] * {stroke:transparent; fill:transparent; color:transparent} .edge-thickness-thick{stroke:transparent}","themeVariables":{"secondaryColor":"transparent","primaryColor":"white","primaryBorderColor":"black"},"flowchart":{"htmlLabels":true, "padding":20, "rankSpacing":20, "nodeSpacing":20}} }%%
flowchart TB
%%accTitle: Titre
%%accDescr: Description
subgraph Argument
direction TB
%% 1("Prémisse")
%% Pour utiliser les guillemets dans une prémisse : #quot;
%% 1 -->|Par conséquent|2
%% 1 & 2 --- PL1((&))
%% C(["Conclusion"])
1("(1) Un embryon 
ou un fœtus est
une personne")
2("(2) Toute 
personne a
droit à la vie")
1 & 2 --- PL1((&))
PL1 --- 3
3("(3) Un embryon 
ou un fœtus a 
droit à la vie")

V1 ==== 3

1.2("(1') Un embryon 
ou un fœtus est un 
individu qui peut 
devenir une personne")
2.2("(2') Tout individu
qui peut devenir 
une personne a 
droit à la vie")
1.2 & 2.2 --- PL1.2((&))
PL1.2 --- 3


4["(4) Si un être a droit à la vie, alors 
tout acte qui a pour conséquence 
d'interrompre la vie de cet être
est moralement inacceptable"]

3 & 4 --- PL2((&))
PL2 --- 5

5["(5) Tout acte qui a pour conséquence 
d'interrompre la vie d'un embryon ou 
d'un fœtus est moralement inacceptable"]

6["(6) L'avortement a pour conséquence 
d'interrompre la vie d'un
embryon ou d'un fœtus "]

5 & 6 --- PL3((&))
V2 === PL3
PL3 --- 7

7["(7) L'avortement est 
moralement inacceptable"]

8["(8) Si un acte est moralement
inacceptable, alors il est
légitime de l'interdire légalement"]

7 & 8 --- PL4((&))
PL4 --- C

C(["Il est légitime
d'interdire légalement
l'avortement"])
end
%% OBJECTIONS

O1["<b>Objection 1 :</b> 
L'embryon n'est pas une personne et le fœtus
n'est une personne qu'à partir du moment T
où il acquiert les caractéristiques C, ce qui
rend légitime l'avortement avant le moment T"]
O1-.-|<i>objection !</i>|1

V3===1.2

O2["<b>Objection 2 :</b> 
Un individu qui peut devenir 
une personne n'a pas le même
statut moral qu'une personne"]
O2-.-|<i>objection !</i>|2.2

V4===2.2
V4===4

O3["<b>Objection 3 :</b> 
Ce n'est pas toujours vrai. Il y a des situations 
analogues où le droit de la personne qui porte
l'enfant prévaut, soit en raison de son droit à la vie,
soit en raison du droit à disposer de son corps (<i>cf.</i> les
expériences de pensée de Judith Jarvis Thompson)"]
O3-...-|<i>objection !</i>|4

O4["<b>Objection 4 :</b> 
L'avortement est l'expulsion de 
l'embryon ou du fœtus hors du corps 
de la personne qui le porte. Avec le
progrès des techniques médicales,
l'avortement pourrait ne pas avoir
pour conséquence l'interruption de
la vie de l'embyron ou du fœtus"]
O4-....-|<i>objection !</i>|6

O5.1["<b>Objection 5.1 :</b> 
L'interdiction légale de l'avortement
est inefficace et met en danger
les personnes qui iront avorter de
manière clandestine"]
O5.1-....-|<i>objection !</i>|8

O5.2["<b>Objection 5.2 :</b> 
L'avortement est une question 
qui relève de la morale et non de 
la loi. On ne peut pas imposer 
l'interdiction de l'avortement en raison 
des conceptions morales personnelles 
que l'on a du bien et du mal."]
O5.2-..-|<i>objection !</i>|8
